GET https://project-spotify.herokuapp.com/albums

###

GET https://project-spotify.herokuapp.com/albums/1

###
GET https://project-spotify.herokuapp.com/albums/save?id=0&name=Tests&authorId=1&year=2014&count=15&length=85&liked=true&picUrl=PictureUrl

###

POST https://project-spotify.herokuapp.com/albums/
Content-Type: application/json

{
  "id": 0,
  "name": "More",
  "authorId": 2,
  "year": 2014,
  "count": 15,
  "length": 85,
  "liked": true,
  "picUrl": "https://img.com/i78asd2k"
}

###

GET https://project-spotify.herokuapp.com/albums/search?name=More

###

DELETE https://project-spotify.herokuapp.com/albums/5

###

###

GET https://project-spotify.herokuapp.com/albums/authors/1


###

GET https://project-spotify.herokuapp.com/author/

###

GET https://project-spotify.herokuapp.com/author/2

###

GET https://project-spotify.herokuapp.com/author
Content-Type: application/json

{
  "id": 0,
  "name": "Logic",
  "picUrl": "https://img.com/i78asd2k"
}

###

DELETE https://project-spotify.herokuapp.com/author/3